### ISSUE TITLE
Issue with bundler 2.0.1

### ISSUE THREAD

**Issue by boratanrikulu** [lab2023/cybele#134]
There is a solution for that.

https://stackoverflow.com/questions/47026174/find-spec-for-exe-cant-find-gem-bundler-0-a-gemgemnotfoundexception

**Comment by vilusa** [comment]
Hi, Bora
Fix this problem: https://github.com/lab2023/cybele/pull/136
During the Docker build process, the new version of Bundler is built into the mold with the Gem install command.
On build process;
![Screenshot from 2019-03-15 00-53-10](https://user-images.githubusercontent.com/8127141/54394293-8673a580-46bd-11e9-824a-e34aeea33982.png)
After the build process, you can no longer run the **bundle install** command
![Screenshot from 2019-03-15 00-53-50](https://user-images.githubusercontent.com/8127141/54394294-8673a580-46bd-11e9-8067-7086a5503b96.png)

**Comment by boratanrikulu** [comment]
The solution is merged. I think we should close this issue.
https://github.com/lab2023/cybele/pull/136

**Comment by ismailakbudak** [comment]
Fixed with v2.3.2
