### ISSUE TITLE
Update README file for fixme link

### ISSUE THREAD

**Issue by ismailakbudak** [lab2023/cybele#137]
We should remove fixme link in README file

<img width="481" alt="Screen Shot 2019-03-18 at 11 10 06" src="https://user-images.githubusercontent.com/4919272/54515888-80f0b680-496e-11e9-9240-a8a458c07639.png">

**Comment by vilusa** [comment]
I fixed this issue and ruby, rails have changed with current version numbers
https://github.com/lab2023/cybele/pull/138
